# EBurNiFication appveyor.yml script

branches:
  only:
    - master

skip_commits:
  files:
    - README.md

version: '{branch}-{build}'
image: Visual Studio 2017

configuration: Release
platform: Any CPU

build:
  parallel: true
  publish_nuget: false
  publish_nuget_symbols: false
  verbosity: minimal
  project: EBurNiFication.sln

#artifacts:
#  - path: 'Eburnification\bin\$(configuration)\*.nupkg'
#
#deploy:
#  provider: NuGet
#  api_key:
#    secure: rEYnR9JThbc6x8DdCo1K8+fgsGKzjNKzTZsldXFLYMm/tFPC7JWWvuKpVTrDBd+g
#  skip_symbols: false
#
#after_test:
#  ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
#
